"""initial schema

Revision ID: 67520b40b3b3
Revises: 
Create Date: 2026-05-31 21:15:26.945637
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '67520b40b3b3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cta_snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tone', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patreon_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('patron_count', sa.Integer(), nullable=False),
    sa.Column('mrr_cents', sa.Integer(), nullable=False),
    sa.Column('new_patrons', sa.Integer(), nullable=False),
    sa.Column('churn_count', sa.Integer(), nullable=False),
    sa.Column('tier_mix_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patreon_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patreon_metrics_captured_at'), ['captured_at'], unique=False)

    op.create_table('patreon_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patreon_tier_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patreon_tiers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patreon_tiers_patreon_tier_id'), ['patreon_tier_id'], unique=True)

    op.create_table('subreddits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('rules_notes', sa.Text(), nullable=True),
    sa.Column('self_promo_ratio', sa.Integer(), nullable=True),
    sa.Column('min_days_between_promos', sa.Integer(), nullable=True),
    sa.Column('last_promo_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subreddits_name'), ['name'], unique=True)

    op.create_table('title_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content_key', sa.String(length=120), nullable=False),
    sa.Column('text', sa.String(length=300), nullable=False),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('title_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_variants_content_key'), ['content_key'], unique=False)

    op.create_table('optimal_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=False),
    sa.Column('engagement_index', sa.Float(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subreddit_id', 'weekday', 'hour')
    )
    with op.batch_alter_table('optimal_windows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimal_windows_subreddit_id'), ['subreddit_id'], unique=False)

    op.create_table('patreon_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patreon_member_id', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'FORMER', 'DECLINED', name='memberstatus'), nullable=False),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('pledge_cents', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_charge_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tier_id'], ['patreon_tiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patreon_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patreon_members_patreon_member_id'), ['patreon_member_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_patreon_members_status'), ['status'], unique=False)

    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=32), nullable=True),
    sa.Column('subreddit_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('chapter_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SCHEDULED', 'POSTED', 'FAILED', name='poststatus'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('permalink', sa.String(length=400), nullable=True),
    sa.Column('title_variant_id', sa.Integer(), nullable=True),
    sa.Column('early_access_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['subreddit_id'], ['subreddits.id'], ),
    sa.ForeignKeyConstraint(['title_variant_id'], ['title_variants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reddit_id')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_posts_status'), ['status'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reddit_id', sa.String(length=32), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author', sa.String(length=64), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_flagged_high_value', sa.Boolean(), nullable=False),
    sa.Column('handled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_post_id'), ['post_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_reddit_id'), ['reddit_id'], unique=True)

    op.create_table('polls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('PLOT', 'NAMING', 'SUGGESTION', name='pollkind'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='pollstatus'), nullable=False),
    sa.Column('opens_at', sa.DateTime(), nullable=False),
    sa.Column('closes_at', sa.DateTime(), nullable=True),
    sa.Column('teaser_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['teaser_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_polls_status'), ['status'], unique=False)

    op.create_table('post_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('num_comments', sa.Integer(), nullable=False),
    sa.Column('upvote_ratio', sa.Float(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_metrics_captured_at'), ['captured_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_metrics_post_id'), ['post_id'], unique=False)

    op.create_table('utm_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('destination_url', sa.String(length=600), nullable=False),
    sa.Column('campaign', sa.String(length=120), nullable=True),
    sa.Column('source', sa.String(length=60), nullable=True),
    sa.Column('medium', sa.String(length=60), nullable=True),
    sa.Column('content', sa.String(length=120), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utm_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utm_links_slug'), ['slug'], unique=True)

    op.create_table('link_clicks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utm_link_id', sa.Integer(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('referer', sa.String(length=400), nullable=True),
    sa.ForeignKeyConstraint(['utm_link_id'], ['utm_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_clicks_clicked_at'), ['clicked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_link_clicks_utm_link_id'), ['utm_link_id'], unique=False)

    op.create_table('poll_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=300), nullable=False),
    sa.Column('vote_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_options_poll_id'), ['poll_id'], unique=False)

    op.create_table('suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patreon_member_id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SHORTLISTED', 'PROMOTED', 'REJECTED', name='suggestionstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patreon_member_id'], ['patreon_members.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suggestions_patreon_member_id'), ['patreon_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_suggestions_status'), ['status'], unique=False)

    op.create_table('conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_click_id', sa.Integer(), nullable=True),
    sa.Column('patreon_member_id', sa.Integer(), nullable=False),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['link_click_id'], ['link_clicks.id'], ),
    sa.ForeignKeyConstraint(['patreon_member_id'], ['patreon_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversions_link_click_id'), ['link_click_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversions_patreon_member_id'), ['patreon_member_id'], unique=False)

    op.create_table('poll_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('poll_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('patreon_member_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('voted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['poll_options.id'], ),
    sa.ForeignKeyConstraint(['patreon_member_id'], ['patreon_members.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poll_id', 'patreon_member_id')
    )
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poll_votes_patreon_member_id'), ['patreon_member_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_poll_votes_poll_id'), ['poll_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_votes_poll_id'))
        batch_op.drop_index(batch_op.f('ix_poll_votes_patreon_member_id'))

    op.drop_table('poll_votes')
    with op.batch_alter_table('conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversions_patreon_member_id'))
        batch_op.drop_index(batch_op.f('ix_conversions_link_click_id'))

    op.drop_table('conversions')
    with op.batch_alter_table('suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_suggestions_patreon_member_id'))

    op.drop_table('suggestions')
    with op.batch_alter_table('poll_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poll_options_poll_id'))

    op.drop_table('poll_options')
    with op.batch_alter_table('link_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_clicks_utm_link_id'))
        batch_op.drop_index(batch_op.f('ix_link_clicks_clicked_at'))

    op.drop_table('link_clicks')
    with op.batch_alter_table('utm_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utm_links_slug'))

    op.drop_table('utm_links')
    with op.batch_alter_table('post_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_metrics_post_id'))
        batch_op.drop_index(batch_op.f('ix_post_metrics_captured_at'))

    op.drop_table('post_metrics')
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polls_status'))

    op.drop_table('polls')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_reddit_id'))
        batch_op.drop_index(batch_op.f('ix_comments_post_id'))

    op.drop_table('comments')
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_posts_status'))

    op.drop_table('posts')
    with op.batch_alter_table('patreon_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patreon_members_status'))
        batch_op.drop_index(batch_op.f('ix_patreon_members_patreon_member_id'))

    op.drop_table('patreon_members')
    with op.batch_alter_table('optimal_windows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_optimal_windows_subreddit_id'))

    op.drop_table('optimal_windows')
    with op.batch_alter_table('title_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_variants_content_key'))

    op.drop_table('title_variants')
    with op.batch_alter_table('subreddits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subreddits_name'))

    op.drop_table('subreddits')
    with op.batch_alter_table('patreon_tiers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patreon_tiers_patreon_tier_id'))

    op.drop_table('patreon_tiers')
    with op.batch_alter_table('patreon_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patreon_metrics_captured_at'))

    op.drop_table('patreon_metrics')
    op.drop_table('cta_snippets')
    # ### end Alembic commands ###
